// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A constraint describes a way to restrict resource's configuration. For
/// example, you could enforce a constraint that controls which Google Cloud
/// services can be activated across an organization, or whether a Compute Engine
/// instance can have serial port connections established. Constraints can be
/// configured by the organization policy administrator to fit the needs of the
/// organization by setting a policy that includes constraints at different
/// locations in the organization's resource hierarchy. Policies are inherited
/// down the resource hierarchy from higher levels, but can also be overridden.
/// For details about the inheritance rules, see
/// [`Policy`][google.cloud.orgpolicy.v2.Policy].
///
/// Constraints have a default behavior determined by the `constraint_default`
/// field, which is the enforcement behavior that is used in the absence of a
/// policy being defined or inherited for the resource in question.
///
/// [google.cloud.orgpolicy.v2.Policy]: <doc:Policy>
public struct Constraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the constraint. Must be in one of
  /// the following forms:
  ///
  /// * `projects/{project_number}/constraints/{constraint_name}`
  /// * `folders/{folder_id}/constraints/{constraint_name}`
  /// * `organizations/{organization_id}/constraints/{constraint_name}`
  ///
  /// For example, "/projects/123/constraints/compute.disableSerialPortAccess".
  public var name: Swift.String = Swift.String()

  /// The human readable name.
  ///
  /// Mutable.
  public var displayName: Swift.String = Swift.String()

  /// Detailed description of what this constraint controls as well as how and
  /// where it is enforced.
  ///
  /// Mutable.
  public var description: Swift.String = Swift.String()

  /// The evaluation behavior of this constraint in the absence of a policy.
  public var constraintDefault: Constraint.ConstraintDefault = Constraint.ConstraintDefault()

  /// Shows if dry run is supported for this constraint or not.
  public var supportsDryRun: Swift.Bool = Swift.Bool()

  /// Managed constraint and canned constraint sometimes can have
  /// equivalents. This field is used to store the equivalent constraint name.
  public var equivalentConstraint: Swift.String = Swift.String()

  /// Shows if simulation is supported for this constraint or not.
  public var supportsSimulation: Swift.Bool = Swift.Bool()

  /// The type of restrictions for this `Constraint`.
  ///
  /// Immutable after creation.
  public var constraintType: OneOf_ConstraintType? = nil

  /// Initialize a new instance of `Constraint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Constraint().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case displayName = "displayName"
    case description = "description"
    case constraintDefault = "constraintDefault"
    case listConstraint = "listConstraint"
    case booleanConstraint = "booleanConstraint"
    case supportsDryRun = "supportsDryRun"
    case equivalentConstraint = "equivalentConstraint"
    case supportsSimulation = "supportsSimulation"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.constraintDefault = try container.decode(
      Constraint.ConstraintDefault.self, forKey: .constraintDefault)
    self.supportsDryRun = try container.decode(Swift.Bool.self, forKey: .supportsDryRun)
    self.equivalentConstraint = try container.decode(
      Swift.String.self, forKey: .equivalentConstraint)
    self.supportsSimulation = try container.decode(Swift.Bool.self, forKey: .supportsSimulation)

    var constraintType: OneOf_ConstraintType? = nil
    let constraintTypeCheckAndSet = {
      if constraintType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'constraintType'"))
      }
      constraintType = $0
    }
    if let listConstraint = try container.decodeIfPresent(
      Constraint.ListConstraint?.self, forKey: .listConstraint)
    {
      try constraintTypeCheckAndSet(.listConstraint(listConstraint))
    }
    if let booleanConstraint = try container.decodeIfPresent(
      Constraint.BooleanConstraint?.self, forKey: .booleanConstraint)
    {
      try constraintTypeCheckAndSet(.booleanConstraint(booleanConstraint))
    }
    self.constraintType = constraintType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.constraintDefault, forKey: .constraintDefault)
    try container.encode(self.supportsDryRun, forKey: .supportsDryRun)
    try container.encode(self.equivalentConstraint, forKey: .equivalentConstraint)
    try container.encode(self.supportsSimulation, forKey: .supportsSimulation)

    if let choice = self.constraintType {
      switch choice {
      case .listConstraint(let value):
        try container.encode(value, forKey: .listConstraint)
      case .booleanConstraint(let value):
        try container.encode(value, forKey: .booleanConstraint)
      }
    }
  }

  /// A constraint type that allows or disallows a list of string values, which
  /// are configured in the
  /// [`PolicyRule`][google.cloud.orgpolicy.v2.PolicySpec.PolicyRule].
  ///
  /// [google.cloud.orgpolicy.v2.PolicySpec.PolicyRule]: <doc:PolicySpec/PolicyRule>
  public struct ListConstraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Indicates whether values grouped into categories can be used in
    /// `Policy.allowed_values` and `Policy.denied_values`. For example,
    /// `"in:Python"` would match any value in the 'Python' group.
    public var supportsIn: Swift.Bool = Swift.Bool()

    /// Indicates whether subtrees of the Resource Manager resource hierarchy
    /// can be used in `Policy.allowed_values` and `Policy.denied_values`. For
    /// example, `"under:folders/123"` would match any resource under the
    /// 'folders/123' folder.
    public var supportsUnder: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `ListConstraint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListConstraint().with { $0.supportsIn = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.orgpolicy.v2.Constraint.ListConstraint"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Custom constraint definition. Defines this as a managed constraint.
  public struct CustomConstraintDefinition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The resource instance type on which this policy applies. Format will be
    /// of the form : `<service name>/<type>` Example:
    ///
    ///  * `compute.googleapis.com/Instance`.
    public var resourceTypes: [Swift.String] = []

    /// All the operations being applied for this constraint.
    public var methodTypes: [Constraint.CustomConstraintDefinition.MethodType] = []

    /// Org policy condition/expression. For example:
    /// `resource.instanceName.matches("[production|test]_.*_(\d)+")` or,
    /// `resource.management.auto_upgrade == true`
    ///
    /// The max length of the condition is 1000 characters.
    public var condition: Swift.String = Swift.String()

    /// Allow or deny type.
    public var actionType: Constraint.CustomConstraintDefinition.ActionType = Constraint
      .CustomConstraintDefinition.ActionType()

    /// Stores the structure of
    /// [`Parameters`][google.cloud.orgpolicy.v2.Constraint.CustomConstraintDefinition.Parameter]
    /// used by the constraint condition. The key of `map` represents the name of
    /// the parameter.
    ///
    /// [google.cloud.orgpolicy.v2.Constraint.CustomConstraintDefinition.Parameter]: <doc:Constraint/CustomConstraintDefinition/Parameter>
    public var parameters: [Swift.String: Constraint.CustomConstraintDefinition.Parameter] = [:]

    /// Initialize a new instance of `CustomConstraintDefinition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomConstraintDefinition().with { $0.resourceTypes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Defines a parameter structure.
    public struct Parameter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Type of the parameter.
      public var type: Constraint.CustomConstraintDefinition.Parameter.Type_ = Constraint
        .CustomConstraintDefinition.Parameter.Type_()

      /// Sets the value of the parameter in an assignment if no value is given.
      public var defaultValue: GoogleCloudWkt.Value? = nil

      /// Provides a CEL expression to specify the acceptable parameter values
      /// during assignment.
      /// For example, parameterName in ("parameterValue1", "parameterValue2")
      public var validValuesExpr: Swift.String = Swift.String()

      /// Defines subproperties primarily used by the UI to display user-friendly
      /// information.
      public var metadata: Constraint.CustomConstraintDefinition.Parameter.Metadata? = nil

      /// Determines the parameter's value structure.
      /// For example, `LIST<STRING>` can be specified by defining `type: LIST`,
      /// and `item: STRING`.
      public var item: Constraint.CustomConstraintDefinition.Parameter.Type_ = Constraint
        .CustomConstraintDefinition.Parameter.Type_()

      /// Initialize a new instance of `Parameter`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Parameter().with { $0.type = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Defines Metadata structure.
      public struct Metadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Detailed description of what this `parameter` is and use of it.
        /// Mutable.
        public var description: Swift.String = Swift.String()

        /// Initialize a new instance of `Metadata`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Metadata().with { $0.description = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.orgpolicy.v2.Constraint.CustomConstraintDefinition.Parameter.Metadata"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// All valid types of parameter.
      public enum Type_: Codable, Equatable, Sendable {
        /// This is only used for distinguishing unset values and should never be
        /// used. Results in an error.
        case unspecified
        /// List parameter type.
        case list
        /// String parameter type.
        case string
        /// Boolean parameter type.
        case boolean
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .list: return 1
          case .string: return 2
          case .boolean: return 3
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "TYPE_UNSPECIFIED"
          case .list: return "LIST"
          case .string: return "STRING"
          case .boolean: return "BOOLEAN"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "TYPE_UNSPECIFIED": self = .unspecified
          case "LIST": self = .list
          case "STRING": self = .string
          case "BOOLEAN": self = .boolean
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .list
          case 2: self = .string
          case 3: self = .boolean
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .list: return try container.encode(1)
          case .string: return try container.encode(2)
          case .boolean: return try container.encode(3)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.orgpolicy.v2.Constraint.CustomConstraintDefinition.Parameter"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// The operation for which this constraint will be applied. To apply this
    /// constraint only when creating new resources, the `method_types` should be
    /// `CREATE` only. To apply this constraint when creating or deleting
    /// resources, the `method_types` should be `CREATE` and `DELETE`.
    ///
    /// `UPDATE`-only custom constraints are not supported. Use `CREATE` or
    /// `CREATE, UPDATE`.
    public enum MethodType: Codable, Equatable, Sendable {
      /// This is only used for distinguishing unset values and should never be
      /// used. Results in an error.
      case unspecified
      /// Constraint applied when creating the resource.
      case create
      /// Constraint applied when updating the resource.
      case update
      /// Constraint applied when deleting the resource.
      /// Not currently supported.
      case delete
      /// Constraint applied when removing an IAM grant.
      case removeGrant
      /// Constraint applied when enforcing forced tagging.
      case governTags
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .create: return 1
        case .update: return 2
        case .delete: return 3
        case .removeGrant: return 4
        case .governTags: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "METHOD_TYPE_UNSPECIFIED"
        case .create: return "CREATE"
        case .update: return "UPDATE"
        case .delete: return "DELETE"
        case .removeGrant: return "REMOVE_GRANT"
        case .governTags: return "GOVERN_TAGS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MethodType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "METHOD_TYPE_UNSPECIFIED": self = .unspecified
        case "CREATE": self = .create
        case "UPDATE": self = .update
        case "DELETE": self = .delete
        case "REMOVE_GRANT": self = .removeGrant
        case "GOVERN_TAGS": self = .governTags
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MethodType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .create
        case 2: self = .update
        case 3: self = .delete
        case 4: self = .removeGrant
        case 5: self = .governTags
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .create: return try container.encode(1)
        case .update: return try container.encode(2)
        case .delete: return try container.encode(3)
        case .removeGrant: return try container.encode(4)
        case .governTags: return try container.encode(5)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Allow or deny type.
    public enum ActionType: Codable, Equatable, Sendable {
      /// This is only used for distinguishing unset values and should never be
      /// used. Results in an error.
      case unspecified
      /// Allowed action type.
      case allow
      /// Deny action type.
      case deny
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .allow: return 1
        case .deny: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ACTION_TYPE_UNSPECIFIED"
        case .allow: return "ALLOW"
        case .deny: return "DENY"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ActionType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ACTION_TYPE_UNSPECIFIED": self = .unspecified
        case "ALLOW": self = .allow
        case "DENY": self = .deny
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ActionType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .allow
        case 2: self = .deny
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .allow: return try container.encode(1)
        case .deny: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.orgpolicy.v2.Constraint.CustomConstraintDefinition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A constraint type is enforced or not enforced, which is configured in the
  /// [`PolicyRule`][google.cloud.orgpolicy.v2.PolicySpec.PolicyRule].
  ///
  /// If `customConstraintDefinition` is defined, this constraint is a managed
  /// constraint.
  ///
  /// [google.cloud.orgpolicy.v2.PolicySpec.PolicyRule]: <doc:PolicySpec/PolicyRule>
  public struct BooleanConstraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Custom constraint definition. Defines this as a managed constraint.
    public var customConstraintDefinition: Constraint.CustomConstraintDefinition? = nil

    /// Initialize a new instance of `BooleanConstraint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BooleanConstraint().with { $0.customConstraintDefinition = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.orgpolicy.v2.Constraint.BooleanConstraint"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Specifies the default behavior in the absence of any policy for the
  /// constraint. This must not be `CONSTRAINT_DEFAULT_UNSPECIFIED`.
  ///
  /// Immutable after creation.
  public enum ConstraintDefault: Codable, Equatable, Sendable {
    /// This is only used for distinguishing unset values and should never be
    /// used. Results in an error.
    case unspecified
    /// Indicate that all values are allowed for list constraints.
    /// Indicate that enforcement is off for boolean constraints.
    case allow
    /// Indicate that all values are denied for list constraints.
    /// Indicate that enforcement is on for boolean constraints.
    case deny
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .allow: return 1
      case .deny: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONSTRAINT_DEFAULT_UNSPECIFIED"
      case .allow: return "ALLOW"
      case .deny: return "DENY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConstraintDefault/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONSTRAINT_DEFAULT_UNSPECIFIED": self = .unspecified
      case "ALLOW": self = .allow
      case "DENY": self = .deny
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConstraintDefault/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .allow
      case 2: self = .deny
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .allow: return try container.encode(1)
      case .deny: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type of restrictions for this `Constraint`.
  ///
  /// Immutable after creation.
  public enum OneOf_ConstraintType: Codable, Equatable, Sendable {
    /// Defines this constraint as being a list constraint.
    indirect case listConstraint(Constraint.ListConstraint?)
    /// Defines this constraint as being a boolean constraint.
    indirect case booleanConstraint(Constraint.BooleanConstraint?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orgpolicy.v2.Constraint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
