// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The response returned from the [ListCustomConstraints]
/// [google.cloud.orgpolicy.v2.OrgPolicy.ListCustomConstraints] method. It will
/// be empty if no custom or managed constraints are set on the organization
/// resource.
public struct ListCustomConstraintsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// All custom and managed constraints that exist on the organization resource.
  /// It will be empty if no custom constraints are set.
  public var customConstraints: [CustomConstraint] = []

  /// Page token used to retrieve the next page. This is currently not used, but
  /// the server may at any point start supplying a valid token.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListCustomConstraintsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCustomConstraintsResponse().with { $0.customConstraints = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orgpolicy.v2.ListCustomConstraintsResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [CustomConstraint] {
    return self.customConstraints
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
