// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol OrgPolicyStub: Sendable {
    func listConstraints(
      request: ListConstraintsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.ListConstraintsResponse

    func listPolicies(
      request: ListPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.ListPoliciesResponse

    func getPolicy(
      request: GetPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    func getEffectivePolicy(
      request: GetEffectivePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    func createPolicy(
      request: CreatePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    func updatePolicy(
      request: UpdatePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    func deletePolicy(
      request: DeletePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createCustomConstraint(
      request: CreateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint

    func updateCustomConstraint(
      request: UpdateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint

    func getCustomConstraint(
      request: GetCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint

    func listCustomConstraints(
      request: ListCustomConstraintsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse

    func deleteCustomConstraint(
      request: DeleteCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
