// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// An interface for managing organization policies.
///
/// The Organization Policy Service provides a simple mechanism for
/// organizations to restrict the allowed configurations across their entire
/// resource hierarchy.
///
/// You can use a policy to configure restrictions on resources. For
/// example, you can enforce a policy that restricts which Google
/// Cloud APIs can be activated in a certain part of your resource
/// hierarchy, or prevents serial port access to VM instances in a
/// particular folder.
///
/// Policies are inherited down through the resource hierarchy. A policy
/// applied to a parent resource automatically applies to all its child resources
/// unless overridden with a policy lower in the hierarchy.
///
/// A constraint defines an aspect of a resource's configuration that can be
/// controlled by an organization's policy administrator. Policies are a
/// collection of constraints that defines their allowable configuration on a
/// particular resource and its child resources.
///
/// @Snippet(path: "OrgPolicyQuickstart")
public class OrgPolicyClient: Clients.OrgPolicyProtocol {
  let inner: any Clients.OrgPolicyStub

  /// Creates a new `OrgPolicyClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.OrgPolicyStub = try Clients.OrgPolicyTransport(options)
    inner = Clients.OrgPolicyRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.OrgPolicyLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists constraints that could be applied on the specified resource.
  ///
  /// @Snippet(path: "OrgPolicy_ListConstraints")
  public func listConstraints(
    request: ListConstraintsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.ListConstraintsResponse {
    try await self.inner.listConstraints(request: request, options: options)
  }

  /// Lists constraints that could be applied on the specified resource.
  ///
  /// @Snippet(path: "OrgPolicy_ListConstraints")
  public func listConstraints(
    byItem: ListConstraintsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Constraint, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudOrgPolicyV2.ListConstraintsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listConstraints(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves all of the policies that exist on a particular resource.
  ///
  /// @Snippet(path: "OrgPolicy_ListPolicies")
  public func listPolicies(
    request: ListPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.ListPoliciesResponse {
    try await self.inner.listPolicies(request: request, options: options)
  }

  /// Retrieves all of the policies that exist on a particular resource.
  ///
  /// @Snippet(path: "OrgPolicy_ListPolicies")
  public func listPolicies(
    byItem: ListPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Policy, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudOrgPolicyV2.ListPoliciesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listPolicies(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a policy on a resource.
  ///
  /// If no policy is set on the resource, `NOT_FOUND` is returned. The
  /// `etag` value can be used with `UpdatePolicy()` to update a
  /// policy during read-modify-write.
  ///
  /// @Snippet(path: "OrgPolicy_GetPolicy")
  public func getPolicy(
    request: GetPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    try await self.inner.getPolicy(request: request, options: options)
  }

  /// Gets the effective policy on a resource. This is the result of merging
  /// policies in the resource hierarchy and evaluating conditions. The
  /// returned policy will not have an `etag` or `condition` set because it is
  /// an evaluated policy across multiple resources.
  /// Subtrees of Resource Manager resource hierarchy with 'under:' prefix will
  /// not be expanded.
  ///
  /// @Snippet(path: "OrgPolicy_GetEffectivePolicy")
  public func getEffectivePolicy(
    request: GetEffectivePolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    try await self.inner.getEffectivePolicy(request: request, options: options)
  }

  /// Creates a policy.
  ///
  /// Returns a `google.rpc.Status` with `google.rpc.Code.NOT_FOUND` if the
  /// constraint does not exist.
  /// Returns a `google.rpc.Status` with `google.rpc.Code.ALREADY_EXISTS` if the
  /// policy already exists on the given Google Cloud resource.
  ///
  /// @Snippet(path: "OrgPolicy_CreatePolicy")
  public func createPolicy(
    request: CreatePolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    try await self.inner.createPolicy(request: request, options: options)
  }

  /// Updates a policy.
  ///
  /// Returns a `google.rpc.Status` with `google.rpc.Code.NOT_FOUND` if the
  /// constraint or the policy do not exist.
  /// Returns a `google.rpc.Status` with `google.rpc.Code.ABORTED` if the etag
  /// supplied in the request does not match the persisted etag of the policy
  ///
  /// Note: the supplied policy will perform a full overwrite of all
  /// fields.
  ///
  /// @Snippet(path: "OrgPolicy_UpdatePolicy")
  public func updatePolicy(
    request: UpdatePolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    try await self.inner.updatePolicy(request: request, options: options)
  }

  /// Deletes a policy.
  ///
  /// Returns a `google.rpc.Status` with `google.rpc.Code.NOT_FOUND` if the
  /// constraint or organization policy does not exist.
  ///
  /// @Snippet(path: "OrgPolicy_DeletePolicy")
  public func deletePolicy(
    request: DeletePolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deletePolicy(request: request, options: options)
  }

  /// Creates a custom constraint.
  ///
  /// Returns a `google.rpc.Status` with `google.rpc.Code.NOT_FOUND` if the
  /// organization does not exist.
  /// Returns a `google.rpc.Status` with `google.rpc.Code.ALREADY_EXISTS` if the
  /// constraint already exists on the given organization.
  ///
  /// @Snippet(path: "OrgPolicy_CreateCustomConstraint")
  public func createCustomConstraint(
    request: CreateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
    try await self.inner.createCustomConstraint(request: request, options: options)
  }

  /// Updates a custom constraint.
  ///
  /// Returns a `google.rpc.Status` with `google.rpc.Code.NOT_FOUND` if the
  /// constraint does not exist.
  ///
  /// Note: the supplied policy will perform a full overwrite of all
  /// fields.
  ///
  /// @Snippet(path: "OrgPolicy_UpdateCustomConstraint")
  public func updateCustomConstraint(
    request: UpdateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
    try await self.inner.updateCustomConstraint(request: request, options: options)
  }

  /// Gets a custom or managed constraint.
  ///
  /// Returns a `google.rpc.Status` with `google.rpc.Code.NOT_FOUND` if the
  /// custom or managed constraint does not exist.
  ///
  /// @Snippet(path: "OrgPolicy_GetCustomConstraint")
  public func getCustomConstraint(
    request: GetCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
    try await self.inner.getCustomConstraint(request: request, options: options)
  }

  /// Retrieves all of the custom constraints that exist on a particular
  /// organization resource.
  ///
  /// @Snippet(path: "OrgPolicy_ListCustomConstraints")
  public func listCustomConstraints(
    request: ListCustomConstraintsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse {
    try await self.inner.listCustomConstraints(request: request, options: options)
  }

  /// Retrieves all of the custom constraints that exist on a particular
  /// organization resource.
  ///
  /// @Snippet(path: "OrgPolicy_ListCustomConstraints")
  public func listCustomConstraints(
    byItem: ListCustomConstraintsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<CustomConstraint, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCustomConstraints(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Deletes a custom constraint.
  ///
  /// Returns a `google.rpc.Status` with `google.rpc.Code.NOT_FOUND` if the
  /// constraint does not exist.
  ///
  /// @Snippet(path: "OrgPolicy_DeleteCustomConstraint")
  public func deleteCustomConstraint(
    request: DeleteCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteCustomConstraint(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `OrgPolicyClient`.
  ///
  /// To mock `OrgPolicyClient` change your functions to receive
  /// `some OrgPolicyProtocol` or `any OrgPolicyProtocol`
  /// and pass a mock implementation in your tests.
  public protocol OrgPolicyProtocol {
    /// See `OrgPolicyClient.listConstraints`.
    func listConstraints(request: ListConstraintsRequest) async throws
      -> GoogleCloudOrgPolicyV2.ListConstraintsResponse

    /// See `OrgPolicyClient.listConstraints`.
    func listConstraints(
      byItem: ListConstraintsRequest
    ) throws -> any AsyncSequence<Constraint, Swift.Error>

    /// See `OrgPolicyClient.listConstraints`.
    func listConstraints(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Constraint, Swift.Error>

    /// See `OrgPolicyClient.listPolicies`.
    func listPolicies(request: ListPoliciesRequest) async throws
      -> GoogleCloudOrgPolicyV2.ListPoliciesResponse

    /// See `OrgPolicyClient.listPolicies`.
    func listPolicies(
      byItem: ListPoliciesRequest
    ) throws -> any AsyncSequence<Policy, Swift.Error>

    /// See `OrgPolicyClient.listPolicies`.
    func listPolicies(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Policy, Swift.Error>

    /// See `OrgPolicyClient.getPolicy`.
    func getPolicy(request: GetPolicyRequest) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.getPolicy`.
    func getPolicy(
      name: Swift.String,
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.getEffectivePolicy`.
    func getEffectivePolicy(request: GetEffectivePolicyRequest) async throws
      -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.getEffectivePolicy`.
    func getEffectivePolicy(
      name: Swift.String,
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.createPolicy`.
    func createPolicy(request: CreatePolicyRequest) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.createPolicy`.
    func createPolicy(
      parent: Swift.String,
      policy: Policy?,
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.updatePolicy`.
    func updatePolicy(request: UpdatePolicyRequest) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.updatePolicy`.
    func updatePolicy(
      policy: Policy?,
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.deletePolicy`.
    func deletePolicy(request: DeletePolicyRequest) async throws

    /// See `OrgPolicyClient.deletePolicy`.
    func deletePolicy(
      name: Swift.String,
    ) async throws

    /// See `OrgPolicyClient.createCustomConstraint`.
    func createCustomConstraint(request: CreateCustomConstraintRequest) async throws
      -> GoogleCloudOrgPolicyV2.CustomConstraint

    /// See `OrgPolicyClient.createCustomConstraint`.
    func createCustomConstraint(
      parent: Swift.String,
      customConstraint: CustomConstraint?,
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint

    /// See `OrgPolicyClient.updateCustomConstraint`.
    func updateCustomConstraint(request: UpdateCustomConstraintRequest) async throws
      -> GoogleCloudOrgPolicyV2.CustomConstraint

    /// See `OrgPolicyClient.updateCustomConstraint`.
    func updateCustomConstraint(
      customConstraint: CustomConstraint?,
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint

    /// See `OrgPolicyClient.getCustomConstraint`.
    func getCustomConstraint(request: GetCustomConstraintRequest) async throws
      -> GoogleCloudOrgPolicyV2.CustomConstraint

    /// See `OrgPolicyClient.getCustomConstraint`.
    func getCustomConstraint(
      name: Swift.String,
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint

    /// See `OrgPolicyClient.listCustomConstraints`.
    func listCustomConstraints(request: ListCustomConstraintsRequest) async throws
      -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse

    /// See `OrgPolicyClient.listCustomConstraints`.
    func listCustomConstraints(
      byItem: ListCustomConstraintsRequest
    ) throws -> any AsyncSequence<CustomConstraint, Swift.Error>

    /// See `OrgPolicyClient.listCustomConstraints`.
    func listCustomConstraints(
      parent: Swift.String,
    ) throws -> any AsyncSequence<CustomConstraint, Swift.Error>

    /// See `OrgPolicyClient.deleteCustomConstraint`.
    func deleteCustomConstraint(request: DeleteCustomConstraintRequest) async throws

    /// See `OrgPolicyClient.deleteCustomConstraint`.
    func deleteCustomConstraint(
      name: Swift.String,
    ) async throws

    /// See `OrgPolicyClient.listConstraints`.
    func listConstraints(
      request: ListConstraintsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.ListConstraintsResponse

    /// See `OrgPolicyClient.listConstraints`.
    func listConstraints(
      byItem: ListConstraintsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Constraint, Swift.Error>

    /// See `OrgPolicyClient.listPolicies`.
    func listPolicies(
      request: ListPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.ListPoliciesResponse

    /// See `OrgPolicyClient.listPolicies`.
    func listPolicies(
      byItem: ListPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Policy, Swift.Error>

    /// See `OrgPolicyClient.getPolicy`.
    func getPolicy(
      request: GetPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.getEffectivePolicy`.
    func getEffectivePolicy(
      request: GetEffectivePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.createPolicy`.
    func createPolicy(
      request: CreatePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.updatePolicy`.
    func updatePolicy(
      request: UpdatePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy

    /// See `OrgPolicyClient.deletePolicy`.
    func deletePolicy(
      request: DeletePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `OrgPolicyClient.createCustomConstraint`.
    func createCustomConstraint(
      request: CreateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint

    /// See `OrgPolicyClient.updateCustomConstraint`.
    func updateCustomConstraint(
      request: UpdateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint

    /// See `OrgPolicyClient.getCustomConstraint`.
    func getCustomConstraint(
      request: GetCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint

    /// See `OrgPolicyClient.listCustomConstraints`.
    func listCustomConstraints(
      request: ListCustomConstraintsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse

    /// See `OrgPolicyClient.listCustomConstraints`.
    func listCustomConstraints(
      byItem: ListCustomConstraintsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<CustomConstraint, Swift.Error>

    /// See `OrgPolicyClient.deleteCustomConstraint`.
    func deleteCustomConstraint(
      request: DeleteCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.OrgPolicyProtocol {
  public func listConstraints(request: ListConstraintsRequest) async throws
    -> GoogleCloudOrgPolicyV2.ListConstraintsResponse
  {
    try await self.listConstraints(request: request, options: .init())
  }

  public func listConstraints(
    request: ListConstraintsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.ListConstraintsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listConstraints(
    byItem: ListConstraintsRequest
  ) throws -> any AsyncSequence<Constraint, Swift.Error> {
    try self.listConstraints(byItem: byItem, options: .init())
  }

  public func listConstraints(
    byItem: ListConstraintsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Constraint, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudOrgPolicyV2.ListConstraintsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConstraints(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Constraint, Swift.Error> {
    let request = ListConstraintsRequest().with {
      $0.parent = parent
    }
    return try self.listConstraints(byItem: request)
  }

  public func listPolicies(request: ListPoliciesRequest) async throws
    -> GoogleCloudOrgPolicyV2.ListPoliciesResponse
  {
    try await self.listPolicies(request: request, options: .init())
  }

  public func listPolicies(
    request: ListPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.ListPoliciesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listPolicies(
    byItem: ListPoliciesRequest
  ) throws -> any AsyncSequence<Policy, Swift.Error> {
    try self.listPolicies(byItem: byItem, options: .init())
  }

  public func listPolicies(
    byItem: ListPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Policy, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudOrgPolicyV2.ListPoliciesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listPolicies(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Policy, Swift.Error> {
    let request = ListPoliciesRequest().with {
      $0.parent = parent
    }
    return try self.listPolicies(byItem: request)
  }

  public func getPolicy(request: GetPolicyRequest) async throws -> GoogleCloudOrgPolicyV2.Policy {
    try await self.getPolicy(request: request, options: .init())
  }

  public func getPolicy(
    request: GetPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getPolicy(
    name: Swift.String,
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    let request = GetPolicyRequest().with {
      $0.name = name
    }
    return try await self.getPolicy(request: request)
  }

  public func getEffectivePolicy(request: GetEffectivePolicyRequest) async throws
    -> GoogleCloudOrgPolicyV2.Policy
  {
    try await self.getEffectivePolicy(request: request, options: .init())
  }

  public func getEffectivePolicy(
    request: GetEffectivePolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEffectivePolicy(
    name: Swift.String,
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    let request = GetEffectivePolicyRequest().with {
      $0.name = name
    }
    return try await self.getEffectivePolicy(request: request)
  }

  public func createPolicy(request: CreatePolicyRequest) async throws
    -> GoogleCloudOrgPolicyV2.Policy
  {
    try await self.createPolicy(request: request, options: .init())
  }

  public func createPolicy(
    request: CreatePolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createPolicy(
    parent: Swift.String,
    policy: Policy?,
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    let request = CreatePolicyRequest().with {
      $0.parent = parent
      $0.policy = policy
    }
    return try await self.createPolicy(request: request)
  }

  public func updatePolicy(request: UpdatePolicyRequest) async throws
    -> GoogleCloudOrgPolicyV2.Policy
  {
    try await self.updatePolicy(request: request, options: .init())
  }

  public func updatePolicy(
    request: UpdatePolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updatePolicy(
    policy: Policy?,
  ) async throws -> GoogleCloudOrgPolicyV2.Policy {
    let request = UpdatePolicyRequest().with {
      $0.policy = policy
    }
    return try await self.updatePolicy(request: request)
  }

  public func deletePolicy(request: DeletePolicyRequest) async throws {
    try await self.deletePolicy(request: request, options: .init())
  }

  public func deletePolicy(
    request: DeletePolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deletePolicy(
    name: Swift.String,
  ) async throws {
    let request = DeletePolicyRequest().with {
      $0.name = name
    }
    try await self.deletePolicy(request: request)
  }

  public func createCustomConstraint(request: CreateCustomConstraintRequest) async throws
    -> GoogleCloudOrgPolicyV2.CustomConstraint
  {
    try await self.createCustomConstraint(request: request, options: .init())
  }

  public func createCustomConstraint(
    request: CreateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCustomConstraint(
    parent: Swift.String,
    customConstraint: CustomConstraint?,
  ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
    let request = CreateCustomConstraintRequest().with {
      $0.parent = parent
      $0.customConstraint = customConstraint
    }
    return try await self.createCustomConstraint(request: request)
  }

  public func updateCustomConstraint(request: UpdateCustomConstraintRequest) async throws
    -> GoogleCloudOrgPolicyV2.CustomConstraint
  {
    try await self.updateCustomConstraint(request: request, options: .init())
  }

  public func updateCustomConstraint(
    request: UpdateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateCustomConstraint(
    customConstraint: CustomConstraint?,
  ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
    let request = UpdateCustomConstraintRequest().with {
      $0.customConstraint = customConstraint
    }
    return try await self.updateCustomConstraint(request: request)
  }

  public func getCustomConstraint(request: GetCustomConstraintRequest) async throws
    -> GoogleCloudOrgPolicyV2.CustomConstraint
  {
    try await self.getCustomConstraint(request: request, options: .init())
  }

  public func getCustomConstraint(
    request: GetCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCustomConstraint(
    name: Swift.String,
  ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
    let request = GetCustomConstraintRequest().with {
      $0.name = name
    }
    return try await self.getCustomConstraint(request: request)
  }

  public func listCustomConstraints(request: ListCustomConstraintsRequest) async throws
    -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse
  {
    try await self.listCustomConstraints(request: request, options: .init())
  }

  public func listCustomConstraints(
    request: ListCustomConstraintsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listCustomConstraints(
    byItem: ListCustomConstraintsRequest
  ) throws -> any AsyncSequence<CustomConstraint, Swift.Error> {
    try self.listCustomConstraints(byItem: byItem, options: .init())
  }

  public func listCustomConstraints(
    byItem: ListCustomConstraintsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<CustomConstraint, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCustomConstraints(
    parent: Swift.String,
  ) throws -> any AsyncSequence<CustomConstraint, Swift.Error> {
    let request = ListCustomConstraintsRequest().with {
      $0.parent = parent
    }
    return try self.listCustomConstraints(byItem: request)
  }

  public func deleteCustomConstraint(request: DeleteCustomConstraintRequest) async throws {
    try await self.deleteCustomConstraint(request: request, options: .init())
  }

  public func deleteCustomConstraint(
    request: DeleteCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCustomConstraint(
    name: Swift.String,
  ) async throws {
    let request = DeleteCustomConstraintRequest().with {
      $0.name = name
    }
    try await self.deleteCustomConstraint(request: request)
  }
}
