// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class OrgPolicyRetry: OrgPolicyStub {
    let inner: any OrgPolicyStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any OrgPolicyStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listConstraints(
      request: ListConstraintsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.ListConstraintsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListConstraintsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.ListConstraintsResponse
          in
          return try await self.inner.listConstraints(request: r, options: o)
        })
    }

    public func listPolicies(
      request: ListPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.ListPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPoliciesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.ListPoliciesResponse
          in
          return try await self.inner.listPolicies(request: r, options: o)
        })
    }

    public func getPolicy(
      request: GetPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.Policy
          in
          return try await self.inner.getPolicy(request: r, options: o)
        })
    }

    public func getEffectivePolicy(
      request: GetEffectivePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEffectivePolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.Policy
          in
          return try await self.inner.getEffectivePolicy(request: r, options: o)
        })
    }

    public func createPolicy(
      request: CreatePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.Policy
          in
          return try await self.inner.createPolicy(request: r, options: o)
        })
    }

    public func updatePolicy(
      request: UpdatePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdatePolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.Policy
          in
          return try await self.inner.updatePolicy(request: r, options: o)
        })
    }

    public func deletePolicy(
      request: DeletePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeletePolicyRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deletePolicy(request: r, options: o)
        })
    }

    public func createCustomConstraint(
      request: CreateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateCustomConstraintRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.CustomConstraint
          in
          return try await self.inner.createCustomConstraint(request: r, options: o)
        })
    }

    public func updateCustomConstraint(
      request: UpdateCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateCustomConstraintRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.CustomConstraint
          in
          return try await self.inner.updateCustomConstraint(request: r, options: o)
        })
    }

    public func getCustomConstraint(
      request: GetCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.CustomConstraint {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCustomConstraintRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.CustomConstraint
          in
          return try await self.inner.getCustomConstraint(request: r, options: o)
        })
    }

    public func listCustomConstraints(
      request: ListCustomConstraintsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCustomConstraintsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOrgPolicyV2.ListCustomConstraintsResponse
          in
          return try await self.inner.listCustomConstraints(request: r, options: o)
        })
    }

    public func deleteCustomConstraint(
      request: DeleteCustomConstraintRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteCustomConstraintRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteCustomConstraint(request: r, options: o)
        })
    }
  }
}
