// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Defines an organization policy which is used to specify constraints
/// for configurations of Google Cloud resources.
public struct Policy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the policy. Must be one of the following
  /// forms, where `constraint_name` is the name of the constraint which this
  /// policy configures:
  ///
  /// * `projects/{project_number}/policies/{constraint_name}`
  /// * `folders/{folder_id}/policies/{constraint_name}`
  /// * `organizations/{organization_id}/policies/{constraint_name}`
  ///
  /// For example, `projects/123/policies/compute.disableSerialPortAccess`.
  ///
  /// Note: `projects/{project_id}/policies/{constraint_name}` is also an
  /// acceptable name for API requests, but responses will return the name using
  /// the equivalent project number.
  public var name: Swift.String = Swift.String()

  /// Basic information about the organization policy.
  public var spec: PolicySpec? = nil

  /// Deprecated.
  @available(*, deprecated)
  public var alternate: AlternatePolicySpec? = nil

  /// Dry-run policy.
  /// Audit-only policy, can be used to monitor how the policy would have
  /// impacted the existing and future resources if it's enforced.
  public var dryRunSpec: PolicySpec? = nil

  /// Optional. An opaque tag indicating the current state of the policy, used
  /// for concurrency control. This 'etag' is computed by the server based on the
  /// value of other fields, and may be sent on update and delete requests to
  /// ensure the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Policy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Policy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let spec = CodingKeys(stringValue: "spec")
    static let alternate = CodingKeys(stringValue: "alternate")
    static let dryRunSpec = CodingKeys(stringValue: "dryRunSpec")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "spec",
      "alternate",
      "dryRunSpec",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.spec = try container.decodeIfPresent(PolicySpec.self, forKey: .spec)
    self.alternate = try container.decodeIfPresent(AlternatePolicySpec.self, forKey: .alternate)
    self.dryRunSpec = try container.decodeIfPresent(PolicySpec.self, forKey: .dryRunSpec)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.spec, forKey: .spec)
    try container.encodeIfPresent(self.alternate, forKey: .alternate)
    try container.encodeIfPresent(self.dryRunSpec, forKey: .dryRunSpec)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orgpolicy.v2.Policy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
